//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.15 at 09:23:42 PM SAST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://entelect.training/incubator/spring-loyalty-service", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package entelect.training.incubator.spring.booking.client.soap;
