spring.application.name=booking-service
client.service.customer.url=http://localhost:8201
client.service.customer.username=admin
client.service.customer.password=is_a_lie

client.service.flight.url=http://localhost:8202
client.service.flight.username=admin
client.service.flight.password=is_a_lie
